services:
  backend:
    build: ./backend
    container_name: backend
    command: flask run --host=0.0.0.0

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - '8080:80'
