services:
  flask:
    build: .
    expose:
      - 5000
    command: flask run --host=0.0.0.0

  frontend:
    image: nginx:stable-alpine
    container_name: frontend
    build:
      context: frontend
    depends_on:
      - flask
    ports:
      - "8080:80"
    environment:
      - DEBUG=False
    restart: always