export const BREWERIES = [
  '7 Fjell Bryggeri',
  'Amundsen Bryggeri',
  'Austmann',
  'Bådin',
  'Cervisiam Bryggeri',
  'Delirium',
  'E.C. Dahls Bryggeri',
  'Estrella Damm',
  'Frydenlund Bryggerier',
  'Færder Mikrobryggeri',
  'Grans Bryggeri',
  'Grünerløkka Brygghus',
  'Haandbryggeriet',
  'Hansa Borg Bryggerier',
  'Het Anker',
  'Hogna Brygg',
  'Huyghe',
  'Inderøy Gårdsbryggeri',
  'Kinn Bryggeri',
  'Liefmans',
  'Mack Juleøl',
  'Macks Ølbryggeri',
  'Midtfyns Bryghus',
  'Monkey Brew',
  'Nøgne Ø Det kompromissløse Bryggeri',
  'Nøisom',
  'Ringnes',
  'S43',
  'To Øl',
  'Wettre Bryggeri',
] as const;

export type Brewery = (typeof BREWERIES)[number];
